package com.github.project;

import static com.codename1.ui.CN.*;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class pooproject extends Lifecycle {
    //Metodo de inicializacion
    @Override
    public void init(Object context) {
        super.init(context);
        // Coloca aquí tu lógica de inicialización
    }
    
    @Override
    public void runApp() {
       new LoginForm().show();
       new InicioConductorForm().show();
       new PantallaPerfilConductor().show();
       new PantallaHistorialConductor().show();
       new InicioGestorForm().show();
       new InicioMonitorForm().show();
    }

    private void hello() {
        Dialog.show("Hello Codename One", "Welcome to Codename One", "OK", null);
    }
}
