package com.github.project;

import com.codename1.system.Lifecycle;
import com.github.project.view.CoordinadorNavegacion;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class pooproject extends Lifecycle {
    //Metodo de inicializacion
    @Override
    public void init(Object context) {
        super.init(context);
        // Coloca aquí tu lógica de inicialización
    }
    
    @Override
    public void runApp() {
        CoordinadorNavegacion.getInstancia().despacharPantallaRaiz();
    }
}
